---
- name: Install Some Utility Software (Test 1)
  become: yes
  hosts: all
  tasks:
    - name: install utility software
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ utility_softwares }}"